### ISSUE TITLE
Linked documentation appears to be missing some steps

### ISSUE THREAD

**Issue by niknaknet** [ZEISS-PiWeb/PiWeb-Import-Sdk#40]
hi
on the linked documentation https://zeiss-piweb.github.io/PiWeb-Import-Sdk/docs/setup/4_development_environment.html there seem to be some steps missing in the description of configuring the IDE for development.  

I am looking to use Visual Studio Community Edition 2022.

there appears to be missing detail in the Download  and install step - as it doesn't describe precisely what needs to be downloaded, and where it should be installed - it's implied that when it is downloaded, it can be installed as a template.

is it a git repo clone? is it a zipfile from somewhere? 

this process is not described in a way that makes it easy for a developer to get started. 

perhaps a full worked example would be useful ?

thanks

Nick

**Comment by daniel-schroeder-zeiss** [comment]
Hello Nick.
While the import sdk itself is now quite stable and ready for the first release, the documentation is still a work in progress. What you are currently seeing is only a rough draft and still missing a lot of content and some revision. The good news here is that setting up the development environment for plugin development is not difficult at all. All you basically need is a working .Net SDK installation. You can download that here https://dotnet.microsoft.com/en-us/download. But since you are using Visual Studio, it will probably take care of installing the SDK anyways.
To make it easier to get started with development, we are going to provide a project template (as you guessed already). However, we don't have that yet. Instead, I would suggest to simply use one of our example projects as a starting point. You can find them in the example directory in this repository.

Note that there is not yet a released PiWeb Auto Importer that can actually run these plugins. The first version of PiWeb supporting import plugins will be 2025.R1 which will be released in the next few weeks.

Feel free to ask any other questions.

**Comment by niknaknet** [comment]
Hi

I had put this on ice for a few weeks, but checked back and found that you had provided the project template - which was easily installed - great work.

Now, I’m looking at getting a copy of the actual AutoImporter that can use the Plugins to nominally attach to a SaaS PiWeb instance for testing.  I had assumed that the most recent (8.6.17.0, dated 8/10/2024) was going to be the right version, but it’s not taking the Registry entry, and nominating a plugin directory results in an ‘Option pluginSearchPaths is unknown’ message.

Do you have any update on the release date for the 2025.R1 release availability?

Best regards,

Nick

**Comment by stephan-scholz-zeiss** [comment]
Hello Nick,

thank you for your interest in the PiWeb Import SDK.
It is true that plug-ins are only supported from version 2015.R1.
The release will be available soon, we hope you have a little more patience.

Best regards
Stephan

**Comment by niknaknet** [comment]
Thanks 

I’ll keep watching !

Nick

**Comment by stephan-scholz-zeiss** [comment]
Hello Nick,

the PiWeb release 2025.R1 is now available in the download portal.
Have fun trying it out. Our documentation should now be in a good usable state, but we are still making improvements.
If you have any questions or suggestions in the future, please do not hesitate to start a new issue or discussion.

Best regards
Stephan
